# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [8]:
import numpy as np
arr = np.arange(2,51,3)
print (arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [25]:
list1 = []
list2 = []
print("Enter List one Element :")
for i in range(5):
    ele = int(input())
    list1.append(ele)

print("Enter List Second Element :")
for i in range(5):
    ele = int(input())
    list2.append(ele)
    
#convert list to numpy array
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = arr1 + arr2 

print()
print(arr1)
print(arr2)
print(arr3)

#sorted array
print()
print(np.sort(arr3))


Enter List one Element :
20
10
30
80
70
Enter List Second Element :
21
41
23
74
52

[20 10 30 80 70]
[21 41 23 74 52]
[ 41  51  53 154 122]

[ 41  51  53 122 154]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [29]:
arr = np.arange(12).reshape((3,4))
print(arr)

#dimension of array
print(arr.ndim)
print(arr.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
12


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [34]:

oneD = np.arange(12).reshape((4,3))
print(oneD)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [36]:
f = np.array([1,2,3,4])
g = np.array([5,6,7,8])


#vertically stack
vst = np.vstack((f,g))
print(vst)

print()
hst = np.hstack((f,g))
print(hst)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]


# Questions 6:
How to get unique items and counts of unique items?

In [41]:
# getting unique items 
arr = [1, 1, 2, 2, 3, 3]
np.unique(arr)


#getting unique items count
arr1 = [1, 1, 2, 2, 3, 3]
unique_elements, counts_elements = np.unique(arr1, return_counts=True)
frequencies = np.asarray((unique_elements , counts_elements)).T
print(frequencies)

[[1 2]
 [2 2]
 [3 2]]
